'use strict'

const paypalConfig = ppConfig()
const faker = require('faker')


module.exports = function ManagedPathMerchantModel() {
    const accountId = Math.random().toString(36).substr(2, 9)
    let newMerchant = {}
        newMerchant.owner_info = {}
        newMerchant.owner_info.email = "pp-mp-examples-" + accountId + "@sandersx.com"
        newMerchant.owner_info.name = {}
        newMerchant.owner_info.name.prefix = faker.name.prefix()
        newMerchant.owner_info.name.given_name = faker.name.firstName()
        newMerchant.owner_info.name.surname = faker.name.lastName()
        newMerchant.owner_info.name.middle_name = faker.name.firstName()
        newMerchant.owner_info.name.suffix = faker.name.suffix()
        newMerchant.owner_info.country_code_of_nationality = "US"
        newMerchant.owner_info.addresses = []
        newMerchant.owner_info.addresses[0] = {}
        newMerchant.owner_info.addresses[0].type = "HOME"
        newMerchant.owner_info.addresses[0].line1 = faker.address.streetAddress()
        newMerchant.owner_info.addresses[0].line2 = faker.address.secondaryAddress()
        newMerchant.owner_info.addresses[0].city = "Gilbert"
        newMerchant.owner_info.addresses[0].state = "AZ"
        newMerchant.owner_info.addresses[0].country_code = "US"
        newMerchant.owner_info.addresses[0].postal_code = "85298"
        newMerchant.owner_info.date_of_birth = "1968-05-12"
        newMerchant.owner_info.ssn = "1234"
        newMerchant.owner_info.phones = []
        newMerchant.owner_info.phones[0] = {}
        newMerchant.owner_info.phones[0].type = "HOME"
        newMerchant.owner_info.phones[0].country_code = "1"
        newMerchant.owner_info.phones[0].national_number = "8882211161"
        newMerchant.owner_info.phones[0].extension_number = ""
        newMerchant.owner_info.phones[1] = {}
        newMerchant.owner_info.phones[1].type = "MOBILE"
        newMerchant.owner_info.phones[1].country_code = "1"
        newMerchant.owner_info.phones[1].national_number = "8882211161"
        newMerchant.owner_info.phones[1].extension_number = ""
        //business_info
        newMerchant.business_info = {}
        newMerchant.business_info.type = "PROPRIETORSHIP"
        newMerchant.business_info.employer_identification_number = "22-2222222"
        newMerchant.business_info.names = []
        newMerchant.business_info.names[0] = {}
        newMerchant.business_info.names[0].type = "LEGAL"
        newMerchant.business_info.names[0].name = faker.company.companyName()
        newMerchant.business_info.names[1] = {}
        newMerchant.business_info.names[1].type = "DOING_BUSINESS_AS"
        newMerchant.business_info.names[1].name = newMerchant.business_info.names[0].name
        newMerchant.business_info.addresses = []
        newMerchant.business_info.addresses[0] = {}
        newMerchant.business_info.addresses[0].type = "WORK"
        newMerchant.business_info.addresses[0].line1 = faker.address.streetAddress()
        newMerchant.business_info.addresses[0].line2 = faker.address.secondaryAddress()
        newMerchant.business_info.addresses[0].city = "Gilbert"
        newMerchant.business_info.addresses[0].state = "AZ"
        newMerchant.business_info.addresses[0].country_code = "US"
        newMerchant.business_info.addresses[0].postal_code = "85298"
        newMerchant.business_info.phones = []
        newMerchant.business_info.phones[0] = {}
        newMerchant.business_info.phones[0].type = "WORK"
        newMerchant.business_info.phones[0].country_code = "1"
        newMerchant.business_info.phones[0].national_number = "8882211161"
        newMerchant.business_info.phones[0].extension_number = ""
        newMerchant.business_info.phones[1] = {}
        newMerchant.business_info.phones[1].type = "BUSINESS"
        newMerchant.business_info.phones[1].country_code = "1"
        newMerchant.business_info.phones[1].national_number = "8882211161"
        newMerchant.business_info.phones[1].extension_number = ""
        newMerchant.business_info.category = "1005"
        newMerchant.business_info.sub_category = "2054"
        newMerchant.business_info.merchant_category_code = "5945"
        newMerchant.business_info.date_business_established = "2001-06-14"
        newMerchant.business_info.date_of_registration = "1997-02-13"
        newMerchant.business_info.dispute_email = paypalConfig.email
        newMerchant.business_info.customer_service = {}
        newMerchant.business_info.customer_service.email = paypalConfig.email
        newMerchant.business_info.customer_service.phone = {}
        newMerchant.business_info.customer_service.phone.country_code = "1"
        newMerchant.business_info.customer_service.phone.national_number = "8882211161"
        newMerchant.business_info.customer_service.phone.extension_number = "1234"
        newMerchant.business_info.business_sales_details = {}
        newMerchant.business_info.business_sales_details.average_price = {}
        newMerchant.business_info.business_sales_details.average_price.minimum_amount = {}
        newMerchant.business_info.business_sales_details.average_price.minimum_amount.currency_code = "USD"
        newMerchant.business_info.business_sales_details.average_price.minimum_amount.value = "123"
    	newMerchant.business_info.business_sales_details.average_price.maximum_amount = {}
        newMerchant.business_info.business_sales_details.average_price.maximum_amount.currency_code = "USD"
        newMerchant.business_info.business_sales_details.average_price.maximum_amount.value = "456"
        newMerchant.business_info.business_sales_details.average_monthly_volume = {}
        newMerchant.business_info.business_sales_details.average_monthly_volume.minimum_amount = {}
        newMerchant.business_info.business_sales_details.average_monthly_volume.minimum_amount.currency_code = "USD"
        newMerchant.business_info.business_sales_details.average_monthly_volume.minimum_amount.value = "1"
        newMerchant.business_info.business_sales_details.average_monthly_volume.maximum_amount = {}
        newMerchant.business_info.business_sales_details.average_monthly_volume.maximum_amount.currency_code = "USD"
        newMerchant.business_info.business_sales_details.average_monthly_volume.maximum_amount.value = "5000"
        newMerchant.business_info.business_sales_details.website = "https://store.watchshop.example.com"
        newMerchant.business_info.business_sales_details.revenue_from_online_sales = {}
        newMerchant.business_info.business_sales_details.revenue_from_online_sales.minimum_percent = "10.0"
        newMerchant.business_info.business_sales_details.revenue_from_online_sales.maximum_percent = "20.0"
        newMerchant.account_currency = "USD"
        newMerchant.account_relations = []
        newMerchant.account_relations[0] = {}
        newMerchant.account_relations[0].type = "PARTNER"
        newMerchant.account_permissions = []
        newMerchant.account_permissions[0] = {}
        newMerchant.account_permissions[0].permissions = []
        newMerchant.account_permissions[0].permissions[0] = "EXPRESS_CHECKOUT"
        newMerchant.account_permissions[0].permissions[1] = "RECURRING_PAYMENT"
        newMerchant.account_permissions[0].permissions[2] = "EXTENDED_PRO_PROCESSING"
        newMerchant.account_permissions[0].permissions[3] = "EXCEPTION_PROCESSING"
        newMerchant.account_permissions[0].permissions[4] = "DISPUTE_RESOLUTION"
        newMerchant.account_permissions[0].permissions[5] = "SETTLEMENT_REPORTING"
        newMerchant.account_permissions[0].permissions[6] = "SHARED_REFUND"
        newMerchant.timezone = "America/Los_Angeles"
        newMerchant.partner_merchant_external_id = faker.random.uuid()
        newMerchant.partner_tax_reporting = true
        

    return newMerchant
}
